# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
#
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  -   id: check-added-large-files
  -   id: check-toml
  -   id: check-yaml
  -   id: end-of-file-fixer
  -   id: trailing-whitespace
- repo: https://github.com/biomejs/pre-commit
  rev: "v0.6.1"  # Use the sha / tag you want to point at
  hooks:
  -   id: biome-check
      files: "\\.(jsx?|tsx?|c(js|ts)|m(js|ts)|d\\.(ts|cts|mts)|jsonc?|css|vue|astro)$"
      additional_dependencies: ["@biomejs/biome@2.3.0"]
